'use client'

import { useState } from 'react'
import {
    Video,
    Sparkles,
    Play,
    Download,
    Share2,
    Wand2,
    Loader2,
    Music,
    Mic,
    Volume2
} from 'lucide-react'
import VideoPlayer from '@/app/remotion/VideoPlayer'
import type { Scene } from '@/app/remotion/SlideshowComposition'

const MUSIC_OPTIONS = [
    { id: 'upbeat', name: 'Upbeat Corporate', url: 'https://files.freemusicarchive.org/storage-freemusicarchive-org/music/no_curator/Tours/Enthusiast/Tours_-_01_-_Enthusiast.mp3' },
    { id: 'cinematic', name: 'Cinematic Epic', url: 'https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Kai_Engel/Satin/Kai_Engel_-_04_-_Sentinel.mp3' },
    { id: 'chill', name: 'Chill Lo-Fi', url: 'https://files.freemusicarchive.org/storage-freemusicarchive-org/music/ccCommunity/Chad_Crouch/Arps/Chad_Crouch_-_Elipses.mp3' },
    { id: 'none', name: 'No Music', url: '' }
]

// Sample voiceover for demo purposes (usually would be generated by AI)
const DEMO_VOICEOVER_URL = 'https://actions.google.com/sounds/v1/alarms/digital_watch_alarm_long.ogg' // Using a sound effect placeholder as I can't guarantee a speech URL is persistent.
// A better simple speech sample
const DEMO_SPEECH_URL = 'https://www2.cs.uic.edu/~i101/SoundFiles/BabyElephantWalk60.wav' // Placeholder

export default function VideoGeneratorPage() {
    const [topic, setTopic] = useState('')
    const [selectedMusic, setSelectedMusic] = useState(MUSIC_OPTIONS[0].id)
    const [useVoiceover, setUseVoiceover] = useState(false)
    const [videoStyle, setVideoStyle] = useState<'slideshow' | 'stock' | 'motion' | 'cinematic'>('stock')
    const [isGenerating, setIsGenerating] = useState(false)
    const [generatedScenes, setGeneratedScenes] = useState<Scene[] | null>(null)
    const [isDownloading, setIsDownloading] = useState(false)

    const generateVideo = async () => {
        if (!topic) return
        setIsGenerating(true)
        setGeneratedScenes(null)

        try {
            const response = await fetch('/api/generate-video', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    topic,
                    style: videoStyle,
                    useVoiceover
                })
            })

            if (!response.ok) {
                const error = await response.json()
                throw new Error(error.error || 'Failed to generate video')
            }

            const data = await response.json()
            setGeneratedScenes(data.scenes)
        } catch (error) {
            console.error('Generation failed:', error)
            alert('Failed to generate video. Check console for details.')
        } finally {
            setIsGenerating(false)
        }
    }

    const handleDownload = async () => {
        if (!generatedScenes) return
        setIsDownloading(true)
        try {
            const response = await fetch('/api/render-video', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    scenes: generatedScenes,
                    style: videoStyle,
                    audioUrl: currentAudioUrl
                })
            })

            if (!response.ok) {
                const errData = await response.json()
                throw new Error(errData.error || 'Download failed')
            }

            // Create blob and trigger download
            const blob = await response.blob()
            const url = window.URL.createObjectURL(blob)
            const a = document.createElement('a')
            a.href = url
            // Use current timestamp for filename
            a.download = `gyrospectrum-${videoStyle}-${Date.now()}.mp4`
            document.body.appendChild(a)
            a.click()
            window.URL.revokeObjectURL(url)
            document.body.removeChild(a)

        } catch (error) {
            console.error('Download error:', error)
            alert('Failed to download video. It might be too long or complex for the dev server.')
        } finally {
            setIsDownloading(false)
        }
    }

    const currentAudioUrl = MUSIC_OPTIONS.find(m => m.id === selectedMusic)?.url

    return (
        <div className="space-y-8 max-w-6xl mx-auto pb-20">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-3xl font-bold text-slate-800 flex items-center gap-3">
                        <Video className="w-8 h-8 text-blue-600" />
                        AI Video Generator
                    </h2>
                    <p className="text-slate-600 mt-2 text-lg">
                        Create professional slideshow videos from text in seconds.
                    </p>
                </div>
            </div>

            {/* Input Section */}
            <div className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
                <div className="max-w-4xl grid grid-cols-1 lg:grid-cols-3 gap-8">
                    <div className="lg:col-span-2 space-y-6">
                        <div>
                            <label className="block text-sm font-bold text-slate-700 mb-2 uppercase tracking-wide">
                                What is your video about?
                            </label>
                            <textarea
                                value={topic}
                                onChange={(e) => setTopic(e.target.value)}
                                placeholder="e.g., Launching our new IoT product line for smart factories..."
                                className="w-full px-6 py-4 text-lg border border-slate-300 rounded-xl focus:outline-none focus:ring-4 focus:ring-blue-100 transition-all font-medium h-32 resize-none"
                                onKeyDown={(e) => {
                                    if (e.key === 'Enter' && !e.shiftKey) {
                                        e.preventDefault();
                                        generateVideo();
                                    }
                                }}
                            />
                        </div>

                        <p className="text-sm text-slate-400 flex items-center gap-2">
                            <Sparkles className="w-4 h-4 text-purple-400" />
                            Uses AI to generate script, select images, and animate.
                        </p>
                    </div>

                    <div className="space-y-6">
                        <label className="block text-sm font-bold text-slate-700 mb-2 uppercase tracking-wide flex items-center gap-2">
                            <Sparkles className="w-4 h-4" />
                            Video Style
                        </label>
                        <div className="grid grid-cols-2 gap-3">
                            <div
                                onClick={() => setVideoStyle('slideshow')}
                                className={`p-3 rounded-xl border cursor-pointer transition-all ${videoStyle === 'slideshow'
                                    ? 'bg-blue-50 border-blue-500 ring-1 ring-blue-500'
                                    : 'bg-white border-slate-200 hover:bg-slate-50'
                                    }`}
                            >
                                <h4 className="font-bold text-slate-800 text-sm">Slideshow</h4>
                                <p className="text-xs text-slate-500 mt-0.5">Images + Zoom</p>
                            </div>
                            <div
                                onClick={() => setVideoStyle('stock')}
                                className={`p-3 rounded-xl border cursor-pointer transition-all ${videoStyle === 'stock'
                                    ? 'bg-blue-50 border-blue-500 ring-1 ring-blue-500'
                                    : 'bg-white border-slate-200 hover:bg-slate-50'
                                    }`}
                            >
                                <h4 className="font-bold text-slate-800 text-sm">Stock Video</h4>
                                <p className="text-xs text-slate-500 mt-0.5">Real Footage</p>
                            </div>
                            <div
                                onClick={() => setVideoStyle('motion')}
                                className={`p-3 rounded-xl border cursor-pointer transition-all ${videoStyle === 'motion'
                                    ? 'bg-blue-50 border-blue-500 ring-1 ring-blue-500'
                                    : 'bg-white border-slate-200 hover:bg-slate-50'
                                    }`}
                            >
                                <h4 className="font-bold text-slate-800 text-sm">Motion FX</h4>
                                <p className="text-xs text-slate-500 mt-0.5">Vox Style</p>
                            </div>
                            <div
                                onClick={() => setVideoStyle('cinematic')}
                                className={`p-3 rounded-xl border cursor-pointer transition-all ${videoStyle === 'cinematic'
                                    ? 'bg-purple-50 border-purple-500 ring-1 ring-purple-500 shadow-md transform scale-[1.02]'
                                    : 'bg-white border-slate-200 hover:bg-slate-50'
                                    }`}
                            >
                                <h4 className="font-bold text-purple-700 text-sm flex items-center gap-1">
                                    <Sparkles className="w-3 h-3" />
                                    Cinematic
                                </h4>
                                <p className="text-xs text-slate-500 mt-0.5">Commercials</p>
                            </div>
                        </div>
                    </div>

                    {/* Voiceover Toggle */}
                    <div>
                        <label className="block text-sm font-bold text-slate-700 mb-2 uppercase tracking-wide flex items-center gap-2">
                            <Mic className="w-4 h-4" />
                            AI Voiceover
                        </label>
                        <div
                            onClick={() => setUseVoiceover(!useVoiceover)}
                            className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer transition-all ${useVoiceover
                                ? 'bg-purple-50 border-purple-500 ring-1 ring-purple-500'
                                : 'bg-white border-slate-200 hover:bg-slate-50'
                                }`}
                        >
                            <div className={`w-5 h-5 rounded border flex items-center justify-center ${useVoiceover ? 'bg-purple-600 border-purple-600' : 'border-slate-300 bg-white'}`}>
                                {useVoiceover && <CheckIcon className="w-3.5 h-3.5 text-white" />}
                            </div>
                            <span className="text-sm font-medium text-slate-700">Generate Narration</span>
                        </div>
                        <p className="text-xs text-slate-400 mt-2 ml-1">
                            Adds AI-generated speech for each scene.
                        </p>
                    </div>

                    {/* Music Selector */}
                    <div>
                        <label className="block text-sm font-bold text-slate-700 mb-2 uppercase tracking-wide flex items-center gap-2">
                            <Music className="w-4 h-4" />
                            Background Music
                        </label>
                        <div className="space-y-2">
                            {MUSIC_OPTIONS.map(option => (
                                <label
                                    key={option.id}
                                    className={`flex items-center gap-3 p-3 rounded-lg border cursor-pointer transition-all ${selectedMusic === option.id
                                        ? 'bg-blue-50 border-blue-500 ring-1 ring-blue-500'
                                        : 'bg-white border-slate-200 hover:bg-slate-50'
                                        }`}
                                >
                                    <input
                                        type="radio"
                                        name="music"
                                        value={option.id}
                                        checked={selectedMusic === option.id}
                                        onChange={(e) => setSelectedMusic(e.target.value)}
                                        className="w-4 h-4 text-blue-600"
                                    />
                                    <span className="text-sm font-medium text-slate-700">{option.name}</span>
                                </label>
                            ))}
                        </div>
                    </div>

                    <button
                        onClick={generateVideo}
                        disabled={!topic || isGenerating}
                        className="w-full px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl font-bold text-lg hover:shadow-lg hover:scale-105 active:scale-95 transition-all disabled:opacity-50 disabled:hover:scale-100 flex items-center gap-2 justify-center"
                    >
                        {isGenerating ? (
                            <>
                                <Loader2 className="w-6 h-6 animate-spin" />
                                Generating...
                            </>
                        ) : (
                            <>
                                <Wand2 className="w-6 h-6" />
                                Generate Video
                            </>
                        )}
                    </button>
                </div>
            </div>

            {/* Results Section */}
            {generatedScenes && (
                <div className="space-y-6 animate-in fade-in slide-in-from-bottom-8 duration-700">
                    <div className="flex items-center justify-between">
                        <h3 className="text-2xl font-bold text-slate-800">Preview</h3>
                        <div className="flex gap-3">
                            <button
                                onClick={handleDownload}
                                disabled={isDownloading}
                                className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 font-medium text-slate-700 transition-colors disabled:opacity-50"
                            >
                                {isDownloading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                                {isDownloading ? 'Rendering...' : 'Download MP4'}
                            </button>
                            <button className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium transition-colors shadow-lg hover:shadow-blue-500/30">
                                <Share2 className="w-4 h-4" />
                                Post to Social
                            </button>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                        {/* The Video Player */}
                        <div className="lg:col-span-2">
                            <VideoPlayer
                                scenes={generatedScenes}
                                audioUrl={currentAudioUrl}
                                autoPlay={true}
                                videoStyle={videoStyle}
                                className="w-full aspect-video shadow-2xl ring-1 ring-slate-900/5 group"
                            />
                        </div>

                        {/* Scene List / Script */}
                        <div className="bg-slate-50 rounded-xl border border-slate-200 p-6 h-full max-h-[500px] overflow-y-auto">
                            <h4 className="font-bold text-slate-700 mb-4 flex items-center gap-2">
                                <Play className="w-4 h-4 text-blue-500" />
                                Video Script
                            </h4>
                            <div className="space-y-4">
                                {generatedScenes.map((scene, idx) => (
                                    <div key={idx} className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm flex gap-4">
                                        <img
                                            src={scene.imageUrl}
                                            alt="scene thumb"
                                            className="w-20 h-20 object-cover rounded-md bg-slate-200"
                                        />
                                        <div>
                                            <div className="flex items-center gap-2">
                                                <span className="text-xs font-bold text-slate-400 uppercase">Scene {idx + 1} ({scene.durationInSeconds}s)</span>
                                                {scene.voiceoverUrl && <Volume2 className="w-3 h-3 text-purple-500" />}
                                            </div>
                                            <p className="font-bold text-slate-800 mt-1">{scene.textTitle}</p>
                                            <p className="text-xs text-slate-500 mt-1 line-clamp-2">{scene.textSubtitle}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            )
            }
        </div >
    )
}

function CheckIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg {...props} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
        </svg>
    )
}
