import { Resend } from 'resend'

// Initialize Resend with API Key
// In production, this comes from process.env.RESEND_API_KEY
const resend = new Resend(process.env.RESEND_API_KEY || 're_dummy_key_for_build_bypass')

export interface EmailPayload {
  to: string
  subject: string
  html: string
}

export async function sendEmail(payload: EmailPayload) {
  try {
    // Check for API key (Simulated for demo if missing)
    if (!process.env.RESEND_API_KEY) {
      console.log('⚠️ [Mock Email Sent] (No API Key configured)')
      console.log('To:', payload.to)
      console.log('Subject:', payload.subject)
      return { success: true, id: 'mock-email-id', error: null }
    }

    const data = await resend.emails.send({
      from: 'GyroSpectrum <onboarding@resend.dev>',
      to: [payload.to],
      subject: payload.subject,
      html: payload.html,
    })

    return { success: true, id: data.data?.id || null, error: null }
  } catch (error) {
    console.error('Email sending failed:', error)
    return { success: false, id: null, error }
  }
}

// Generate the "Welcome Video" HTML Template
export function generateWelcomeEmailHtml(userName: string, videoUrl: string) {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; }
          .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 40px; border-radius: 12px; margin-top: 40px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
          .header { text-align: center; margin-bottom: 30px; }
          .logo { width: 50px; height: 50px; background: linear-gradient(135deg, #2563eb 0%, #7c3aed 100%); border-radius: 10px; display: inline-block; margin-bottom: 20px; }
          .title { color: #1e293b; font-size: 24px; font-weight: bold; margin-bottom: 10px; }
          .text { color: #475569; font-size: 16px; line-height: 1.6; margin-bottom: 20px; }
          .video-card { background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; text-align: center; margin: 30px 0; }
          .button { display: inline-block; background: linear-gradient(90deg, #2563eb 0%, #7c3aed 100%); color: #ffffff; text-decoration: none; padding: 12px 30px; border-radius: 8px; font-weight: bold; margin-top: 20px; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <div class="logo"></div>
            <h1 class="title">Welcome to GyroSpectrum, ${userName}! 👋</h1>
          </div>
          
          <p class="text">
            Thanks for checking out our platform. We've used our AI engine to generate a personalized introduction video just for you.
          </p>
          
          <div class="video-card">
            <img src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=600&auto=format&fit=crop" style="width: 100%; border-radius: 8px; margin-bottom: 15px;" alt="Video Preview" />
            <h3 style="margin: 0; color: #1e293b;">Your Personalized Intro</h3>
            <p style="color: #64748b; font-size: 14px; margin-top: 5px;">Generated by GyroSpectrum AI • 0:45</p>
            <a href="${videoUrl}" class="button">Watch Video</a>
          </div>
          
          <p class="text">
            Ready to automate your marketing? Click the button above to see how we can help specific to your needs.
          </p>
          
          <div class="footer">
            © 2026 GyroSpectrum AI Marketing. All rights reserved.<br>
            123 Innovation Drive, Tech City, TC 90210
          </div>
        </div>
      </body>
    </html>
  `
}
