#!/usr/bin/env node

/**
 * GyroSpectrum Setup Wizard
 * Interactive setup for environment variables
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const question = (prompt) => {
    return new Promise((resolve) => {
        rl.question(prompt, resolve);
    });
};

const colors = {
    reset: '\x1b[0m',
    bright: '\x1b[1m',
    green: '\x1b[32m',
    blue: '\x1b[34m',
    yellow: '\x1b[33m',
    cyan: '\x1b[36m',
};

async function main() {
    console.log(`\n${colors.bright}${colors.blue}🚀 GyroSpectrum Setup Wizard${colors.reset}\n`);
    console.log('This wizard will help you configure your environment variables.\n');

    const config = {};

    // Supabase Configuration
    console.log(`${colors.cyan}--- Supabase Configuration ---${colors.reset}`);
    console.log('Get these from: https://supabase.com → Your Project → Settings → API\n');

    config.NEXT_PUBLIC_SUPABASE_URL = await question('Supabase Project URL: ');
    config.NEXT_PUBLIC_SUPABASE_ANON_KEY = await question('Supabase Anon Key: ');
    config.SUPABASE_SERVICE_ROLE_KEY = await question('Supabase Service Role Key: ');

    // Google Gemini Configuration
    console.log(`\n${colors.cyan}--- Google Gemini AI Configuration ---${colors.reset}`);
    console.log('Get this from: https://ai.google.dev\n');

    config.GOOGLE_GEMINI_API_KEY = await question('Google Gemini API Key: ');

    // Application URL
    console.log(`\n${colors.cyan}--- Application Configuration ---${colors.reset}\n`);

    const useLocalhost = await question('Running locally? (y/n): ');
    if (useLocalhost.toLowerCase() === 'y') {
        config.NEXT_PUBLIC_APP_URL = 'http://localhost:3000';
    } else {
        config.NEXT_PUBLIC_APP_URL = await question('Production URL: ');
    }

    // Optional Social Media APIs
    console.log(`\n${colors.cyan}--- Social Media APIs (Optional - Press Enter to skip) ---${colors.reset}\n`);

    config.FACEBOOK_APP_ID = await question('Facebook App ID (optional): ');
    config.FACEBOOK_APP_SECRET = await question('Facebook App Secret (optional): ');
    config.INSTAGRAM_ACCESS_TOKEN = await question('Instagram Access Token (optional): ');
    config.LINKEDIN_CLIENT_ID = await question('LinkedIn Client ID (optional): ');
    config.LINKEDIN_CLIENT_SECRET = await question('LinkedIn Client Secret (optional): ');
    config.TIKTOK_CLIENT_KEY = await question('TikTok Client Key (optional): ');
    config.TIKTOK_CLIENT_SECRET = await question('TikTok Client Secret (optional): ');
    config.WHATSAPP_BUSINESS_ACCOUNT_ID = await question('WhatsApp Business Account ID (optional): ');
    config.WHATSAPP_ACCESS_TOKEN = await question('WhatsApp Access Token (optional): ');

    // Generate .env.local content
    let envContent = '# GyroSpectrum Environment Variables\n';
    envContent += '# Generated by setup wizard\n\n';

    envContent += '# Supabase\n';
    envContent += `NEXT_PUBLIC_SUPABASE_URL=${config.NEXT_PUBLIC_SUPABASE_URL}\n`;
    envContent += `NEXT_PUBLIC_SUPABASE_ANON_KEY=${config.NEXT_PUBLIC_SUPABASE_ANON_KEY}\n`;
    envContent += `SUPABASE_SERVICE_ROLE_KEY=${config.SUPABASE_SERVICE_ROLE_KEY}\n\n`;

    envContent += '# Google Gemini AI\n';
    envContent += `GOOGLE_GEMINI_API_KEY=${config.GOOGLE_GEMINI_API_KEY}\n\n`;

    if (config.FACEBOOK_APP_ID || config.INSTAGRAM_ACCESS_TOKEN ||
        config.LINKEDIN_CLIENT_ID || config.TIKTOK_CLIENT_KEY ||
        config.WHATSAPP_BUSINESS_ACCOUNT_ID) {
        envContent += '# Social Media APIs\n';
        if (config.FACEBOOK_APP_ID) envContent += `FACEBOOK_APP_ID=${config.FACEBOOK_APP_ID}\n`;
        if (config.FACEBOOK_APP_SECRET) envContent += `FACEBOOK_APP_SECRET=${config.FACEBOOK_APP_SECRET}\n`;
        if (config.INSTAGRAM_ACCESS_TOKEN) envContent += `INSTAGRAM_ACCESS_TOKEN=${config.INSTAGRAM_ACCESS_TOKEN}\n`;
        if (config.LINKEDIN_CLIENT_ID) envContent += `LINKEDIN_CLIENT_ID=${config.LINKEDIN_CLIENT_ID}\n`;
        if (config.LINKEDIN_CLIENT_SECRET) envContent += `LINKEDIN_CLIENT_SECRET=${config.LINKEDIN_CLIENT_SECRET}\n`;
        if (config.TIKTOK_CLIENT_KEY) envContent += `TIKTOK_CLIENT_KEY=${config.TIKTOK_CLIENT_KEY}\n`;
        if (config.TIKTOK_CLIENT_SECRET) envContent += `TIKTOK_CLIENT_SECRET=${config.TIKTOK_CLIENT_SECRET}\n`;
        if (config.WHATSAPP_BUSINESS_ACCOUNT_ID) envContent += `WHATSAPP_BUSINESS_ACCOUNT_ID=${config.WHATSAPP_BUSINESS_ACCOUNT_ID}\n`;
        if (config.WHATSAPP_ACCESS_TOKEN) envContent += `WHATSAPP_ACCESS_TOKEN=${config.WHATSAPP_ACCESS_TOKEN}\n`;
        envContent += '\n';
    }

    envContent += '# Application\n';
    envContent += `NEXT_PUBLIC_APP_URL=${config.NEXT_PUBLIC_APP_URL}\n`;

    // Write to .env.local
    const envPath = path.join(process.cwd(), '.env.local');

    console.log(`\n${colors.yellow}📝 Writing configuration to .env.local...${colors.reset}`);

    try {
        fs.writeFileSync(envPath, envContent);
        console.log(`${colors.green}✅ Configuration saved successfully!${colors.reset}\n`);

        console.log(`${colors.bright}Next steps:${colors.reset}`);
        console.log('1. Review your .env.local file');
        console.log('2. Run the database migration in Supabase');
        console.log('3. Start the dev server: npm run dev\n');

        console.log(`${colors.cyan}💡 Tip: Never commit .env.local to git!${colors.reset}\n`);
    } catch (error) {
        console.error(`${colors.red}❌ Error writing .env.local:${colors.reset}`, error.message);
    }

    rl.close();
}

main().catch(console.error);
